### ISSUE TITLE
Mining target (nBits) should be in the PoW data, not block header

### ISSUE THREAD

**Issue by domob1812** [xaya/Specs#1]
A small issue with the proposed dual-algo, "triple-purpose" mining:  Since the "pure" block header itself does not carry information about which algo is used, it does not make much sense to put the difficulty target (`nBits`) in it.  Especially in light of mining with `getauxblock` and `getwork`, it might make sense to share the block generation logic so that the same generated blocks can be returned by either method.

Instead of having the difficulty target in `nBits` in the pure block header, we should let `nBits` be free (or perhaps restrict it to be zero, so that we may use it in a controlled way if we later want to).  Instead, the **PoW data**, which also specifies the mining algo, should have the `nBits`.  All other validation rules stay the same (i. e., when verifying a block, we check that the `nBits` *in the PoW data* are as expected for the given algo, and then that the supplied PoW matches the target).

**Comment by ploynapa28** [comment]
Ii
