### ISSUE TITLE
Define address restrictions

### ISSUE THREAD

**Issue by domob1812** [xaya/Specs#3]
It would be very useful to allow people to place "restrictions" on receiving coins to specific addresses (e.g. that only one transaction can be received).  Implementing this as a soft fork will enable better in-game market places, as unique items could be sold for CHI in the game state without the possibility of getting paid twice in CHI and the need for "locking" or refunding.

Here's roughly how I think those address restrictions should work:

- They are only temporary with a configurable (but bounded-from-above) number of blocks for which they are valid.  This avoids the need to keep restrictions in the network state forever.
- Restrictions are defined by updating a name with a specific JSON in the value.  The restriction will be put on the address that owned the name before the update, making sure that only the owner of an address can restrict it.
- Restrictions can define (at the minimum) a maximum number of transactions to the address, a minimum amount per transaction and a maximum total balance sent.  This is enough to build a decent in-game market place.
- Restrictions are part of the consensus rules for which transactions are valid.  Adding them will be a soft fork.

This should be fleshed out in more detail in a proper spec.

**Comment by domob1812** [comment]
@xaya - do you think this sounds like a good plan (from the few details given already in the issue post)?  Is there anything I'm missing, or would that be all we need for now?

**Comment by xaya** [comment]
Yes this seems perfect.

**Comment by xaya** [comment]
If someone has 1000 quantity of an asset for sale, it would be good it were also possible to buy those 1000 with 1 tx. i.e. specify the quantity.

to reduce no transactions
+
create some sort of orderbook/market place.

**Comment by domob1812** [comment]
Sure, you can do that in the game state.  With the restrictions proposed here, you can implement this on the game side.

**Comment by domob1812** [comment]
This has now been written in a first version: https://github.com/xaya/Specs/blob/master/addressrestrictions.md
